### ISSUE TITLE
how to evaluate my dialog-level data

### ISSUE THREAD

**Issue by 18166035475** [e0397123/DynaEval#1]
Hi:
   if i want to use DynaEval to evaluate other dataset(for example,persona-see-dial), what should i do?

**Comment by e0397123** [comment]
Hi, you may process the dataset into the same format as the fed data and use "score.sh" to obtain the metric scores of each dialogue.

**Comment by e0397123** [comment]
I have a processed version of the persona-see-dial, which I can email to you if you need it.

**Comment by 18166035475** [comment]
ok thank you! my email : 1204581631@qq.com

**Comment by e0397123** [comment]
> ok thank you! my email : [1204581631@qq.com](mailto:1204581631@qq.com)

email sent
